# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b12ee72409f8289f3b381b6bd223336088d153003e3abd1be45ee64e8d2b5d871b83428254bc13d64bfb404299d7b80309378d70f438a39aecfe96b1407f2fa

test:
  secret_key_base: 44877438f3da825f7e42fa150e2b8bd0d4284d5500b9a40c6e3526b084dc9cdd110b065640de2a42df8553518ac83bc7eda1f2abad6829aad1922fea4b90d056

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
